import os
import argparse
from paddleocr import PaddleOCRVL

def run_ocr(image_path):
    print(f"[*] Checking if file exists: {image_path}")
    if not os.path.exists(image_path):
        print(f"[Error] Image file '{image_path}' not found.")
        return

    print("[*] Initializing SOTA PaddleOCR-VL (v1.6)...")
    print("[!] Note: The first run will automatically download weights from Hugging Face.")
    
    try:
        # Initialize the pipeline using the 1.6 architecture
        pipeline = PaddleOCRVL(pipeline_version="v1.6")
        
        print(f"[*] Running prediction on: {image_path}")
        output = pipeline.predict(image_path)
        
        if not output:
            print("[Error] No output generated by PaddleOCR-VL.")
            return

        print("\n" + "="*50 + "\n[+] RAW EXTRACTION RESULTS\n" + "="*50)
        for i, res in enumerate(output):
            print(f"\n--- Layer/Page {i + 1} ---")
            
            # Check for structural markdown field safely
            extracted_text = ""
            if hasattr(res, "markdown") and res.markdown:
                extracted_text = res.markdown
            elif isinstance(res, dict) and "markdown" in res:
                extracted_text = res["markdown"]
                
            if extracted_text:
                print(extracted_text)
            else:
                # Fallback to default rendering if markdown string isn't populated directly
                try:
                    res.print()
                except Exception:
                    print(res)
            
            # Save layout parsing locally for direct inspection
            output_dir = "ocr_test_output"
            res.save_to_markdown(save_path=output_dir)
            print(f"\n[Info] Saved structured markdown folder to: ./{output_dir}")
            
        print("\n" + "="*50)

    except Exception as e:
        print(f"[Error] PaddleOCR-VL execution failed: {e}")
        print("[Suggestion] If encountering binary or architecture errors on Windows 11, verify that MSVC Build Tools are installed.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Standalone PaddleOCR-VL Verification")
    parser.add_argument("image_path", help="Local path to the test math/document image.")
    args = parser.parse_args()
    
    run_ocr(args.image_path) 